### ISSUE TITLE
Missing directory: game_files

### ISSUE THREAD

**Issue by M4DJekyll** [Nergon/SecretHitlerDiscord#1]
Tried to make a custom bot with the code, and I'm able to load the lobbies and get enough players into the game. When I try to start the game though, there's an error that says that the game_files directory can't be found. In the files itself, there is no games_files directory, so I'm not exactly sure what's going on here. Please let me know if there's something I'm doing wrong!

**Comment by Nergon** [comment]
Just create the folder game_files ("mkdir game_files"). Then everything should work
